//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ai_image_generations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub batch_id: String,
    pub config_key: String,
    pub config_name: String,
    pub prompt: String,
    pub model: String,
    pub size: String,
    pub quality: String,
    pub output_index: i32,
    pub save_mode: String,
    pub storage_profile_id: Option<i32>,
    pub storage_bucket_id: Option<i32>,
    pub output_upload_file_id: Option<i32>,
    pub local_output_path: Option<String>,
    pub original_name: String,
    pub mime_type: Option<String>,
    pub status: String,
    pub error_message: Option<String>,
    pub reference_summary: Option<String>,
    pub reference_count: i32,
    pub created_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::storage_profiles::Entity",
        from = "Column::StorageProfileId",
        to = "super::storage_profiles::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StorageProfiles,
    #[sea_orm(
        belongs_to = "super::storage_buckets::Entity",
        from = "Column::StorageBucketId",
        to = "super::storage_buckets::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StorageBuckets,
    #[sea_orm(
        belongs_to = "super::upload_files::Entity",
        from = "Column::OutputUploadFileId",
        to = "super::upload_files::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    UploadFiles,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::storage_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageProfiles.def()
    }
}

impl Related<super::storage_buckets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageBuckets.def()
    }
}

impl Related<super::upload_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadFiles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
