//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_runs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub template_id: Option<i32>,
    pub name: String,
    pub working_directory: String,
    pub command_line: String,
    pub effective_script: String,
    pub status: String,
    pub exit_code: Option<i32>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    pub triggered_by: String,
    pub created_by: Option<i32>,
    pub error_message: Option<String>,
    pub output_tail: Option<String>,
    pub preview_path_template: Option<String>,
    pub preview_path: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::command_templates::Entity",
        from = "Column::TemplateId",
        to = "super::command_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommandTemplates,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CreatedByUsers,
}

impl Related<super::command_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandTemplates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
