//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_run_logs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub run_id: i32,
    pub seq: i32,
    pub stream: String,
    pub chunk: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::command_runs::Entity",
        from = "Column::RunId",
        to = "super::command_runs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CommandRuns,
}

impl Related<super::command_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandRuns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
