//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_workflow_run_steps")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub workflow_run_id: i32,
    pub workflow_step_id: Option<i32>,
    pub command_run_id: Option<i32>,
    pub step_name: String,
    pub sort_order: i32,
    pub status: String,
    pub resolved_args: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::command_workflow_runs::Entity",
        from = "Column::WorkflowRunId",
        to = "super::command_workflow_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommandWorkflowRuns,
    #[sea_orm(
        belongs_to = "super::command_workflow_steps::Entity",
        from = "Column::WorkflowStepId",
        to = "super::command_workflow_steps::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommandWorkflowSteps,
    #[sea_orm(
        belongs_to = "super::command_runs::Entity",
        from = "Column::CommandRunId",
        to = "super::command_runs::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommandRuns,
}

impl Related<super::command_workflow_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflowRuns.def()
    }
}

impl Related<super::command_workflow_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflowSteps.def()
    }
}

impl Related<super::command_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandRuns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
