//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_workflow_steps")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub workflow_id: i32,
    pub template_id: i32,
    pub name: String,
    pub sort_order: i32,
    pub args: Option<String>,
    pub env_vars: Option<String>,
    pub working_directory: Option<String>,
    pub timeout_seconds: Option<i32>,
    pub enabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::command_workflows::Entity",
        from = "Column::WorkflowId",
        to = "super::command_workflows::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommandWorkflows,
    #[sea_orm(
        belongs_to = "super::command_templates::Entity",
        from = "Column::TemplateId",
        to = "super::command_templates::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommandTemplates,
    #[sea_orm(has_many = "super::command_workflow_run_steps::Entity")]
    CommandWorkflowRunSteps,
}

impl Related<super::command_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflows.def()
    }
}

impl Related<super::command_templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandTemplates.def()
    }
}

impl Related<super::command_workflow_run_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflowRunSteps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
