//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "command_workflow_runs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub workflow_id: Option<i32>,
    pub name: String,
    pub status: String,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    pub created_by: Option<i32>,
    pub error_message: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::command_workflows::Entity",
        from = "Column::WorkflowId",
        to = "super::command_workflows::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommandWorkflows,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CreatedByUsers,
    #[sea_orm(has_many = "super::command_workflow_run_steps::Entity")]
    CommandWorkflowRunSteps,
}

impl Related<super::command_workflows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflows.def()
    }
}

impl Related<super::command_workflow_run_steps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommandWorkflowRunSteps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
