//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "content_articles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub category_id: i32,
    pub title: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub summary: Option<String>,
    pub content: String,
    pub cover_image_url: Option<String>,
    pub status: String,
    pub is_featured: bool,
    pub published_at: Option<DateTimeWithTimeZone>,
    pub seo_title: Option<String>,
    pub seo_description: Option<String>,
    pub created_by: Option<i32>,
    pub updated_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::content_categories::Entity",
        from = "Column::CategoryId",
        to = "super::content_categories::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ContentCategories,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CreatedByUsers,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UpdatedByUsers,
}

impl Related<super::content_categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentCategories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
