//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "database_restores")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub backup_id: i32,
    pub status: String,
    pub confirm_phrase: String,
    pub pre_restore_backup_id: Option<i32>,
    pub started_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    pub output: Option<String>,
    pub error_message: Option<String>,
    pub restored_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::database_backups::Entity",
        from = "Column::BackupId",
        to = "super::database_backups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DatabaseBackups,
    #[sea_orm(
        belongs_to = "super::database_backups::Entity",
        from = "Column::PreRestoreBackupId",
        to = "super::database_backups::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PreRestoreDatabaseBackups,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RestoredBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::database_backups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DatabaseBackups.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
