//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "dict_items")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub label: String,
    pub value: String,
    pub color: Option<String>,
    pub extra: Option<String>,
    pub enabled: bool,
    pub is_default: bool,
    pub sort_order: i32,
    pub dict_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dict_types::Entity",
        from = "Column::DictTypeId",
        to = "super::dict_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DictTypes,
}

impl Related<super::dict_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DictTypes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
