//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod data_scopes;
pub mod database_backups;
pub mod dict_items;
pub mod dict_types;
pub mod email_templates;
pub mod menus;
pub mod operation_logs;
pub mod permissions;
pub mod prelude;
pub mod rate_limit_events;
pub mod rate_limit_rules;
pub mod refresh_tokens;
pub mod role_data_scopes;
pub mod role_menus;
pub mod role_permissions;
pub mod roles;
pub mod scheduled_task_runs;
pub mod scheduled_tasks;
pub mod system_notifications;
pub mod system_settings;
pub mod tenants;
pub mod upload_files;
pub mod user_roles;
pub mod users;
