//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod data_scopes;
pub mod dict_items;
pub mod dict_types;
pub mod menus;
pub mod operation_logs;
pub mod permissions;
pub mod prelude;
pub mod refresh_tokens;
pub mod role_data_scopes;
pub mod role_menus;
pub mod role_permissions;
pub mod roles;
pub mod system_settings;
pub mod tenants;
pub mod upload_files;
pub mod user_roles;
pub mod users;
