//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_orders")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub order_no: String,
    pub merchant_order_no: Option<String>,
    pub subject: String,
    pub body: Option<String>,
    pub amount: String,
    pub currency: String,
    pub provider: String,
    pub status: String,
    pub paid_at: Option<DateTimeWithTimeZone>,
    pub expired_at: Option<DateTimeWithTimeZone>,
    pub client_ip: Option<String>,
    pub payer_id: Option<String>,
    pub trade_no: Option<String>,
    pub metadata: Option<String>,
    pub tenant_id: Option<i32>,
    pub channel_id: Option<i32>,
    pub created_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::payment_channels::Entity",
        from = "Column::ChannelId",
        to = "super::payment_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PaymentChannels,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CreatedByUser,
}

impl Related<super::payment_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
