//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "payment_refunds")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub refund_no: String,
    pub amount: String,
    pub reason: Option<String>,
    pub status: String,
    pub provider_refund_no: Option<String>,
    pub reviewed_at: Option<DateTimeWithTimeZone>,
    pub metadata: Option<String>,
    pub tenant_id: Option<i32>,
    pub payment_order_id: i32,
    pub requested_by: Option<i32>,
    pub reviewed_by: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::payment_orders::Entity",
        from = "Column::PaymentOrderId",
        to = "super::payment_orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PaymentOrders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::RequestedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    RequestedByUser,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ReviewedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ReviewedByUser,
}

impl Related<super::payment_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentOrders.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
