//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::data_scopes::Entity as DataScopes;
pub use super::dict_items::Entity as DictItems;
pub use super::dict_types::Entity as DictTypes;
pub use super::menus::Entity as Menus;
pub use super::operation_logs::Entity as OperationLogs;
pub use super::permissions::Entity as Permissions;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::role_data_scopes::Entity as RoleDataScopes;
pub use super::role_menus::Entity as RoleMenus;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::system_settings::Entity as SystemSettings;
pub use super::tenants::Entity as Tenants;
pub use super::upload_files::Entity as UploadFiles;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
