//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

#![allow(clippy::struct_excessive_bools)]

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "role_menus")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub menu_id: i32,
    pub can_create: bool,
    pub can_update: bool,
    pub can_delete: bool,
    pub can_import: bool,
    pub can_export: bool,
    pub can_print: bool,
    pub can_help: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::roles::Entity",
        from = "Column::RoleId",
        to = "super::roles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Roles,
    #[sea_orm(
        belongs_to = "super::menus::Entity",
        from = "Column::MenuId",
        to = "super::menus::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Menus,
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::menus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Menus.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
