//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "scheduled_task_runs")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub task_id: i32,
    pub code: String,
    pub status: String,
    pub started_at: DateTimeWithTimeZone,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    pub output: Option<String>,
    pub error_message: Option<String>,
    pub triggered_by: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::scheduled_tasks::Entity",
        from = "Column::TaskId",
        to = "super::scheduled_tasks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduledTasks,
}

impl Related<super::scheduled_tasks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduledTasks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
