//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "storage_profiles")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tenant_id: i32,
    pub name: String,
    pub code: String,
    pub provider: String,
    pub enabled: bool,
    pub is_default: bool,
    pub endpoint: Option<String>,
    pub region: Option<String>,
    pub access_key_id: Option<String>,
    pub secret_access_key: Option<String>,
    pub public_base_url: Option<String>,
    pub path_style: bool,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::storage_buckets::Entity")]
    StorageBuckets,
    #[sea_orm(has_many = "super::upload_files::Entity")]
    UploadFiles,
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::storage_buckets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageBuckets.def()
    }
}

impl Related<super::upload_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
