//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "storage_buckets")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub storage_profile_id: i32,
    pub tenant_id: i32,
    pub name: String,
    pub bucket: String,
    pub base_prefix: Option<String>,
    pub local_root: Option<String>,
    pub public_prefix: Option<String>,
    pub enabled: bool,
    pub is_default: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::storage_profiles::Entity",
        from = "Column::StorageProfileId",
        to = "super::storage_profiles::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StorageProfiles,
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tenants,
    #[sea_orm(has_many = "super::upload_files::Entity")]
    UploadFiles,
}

impl Related<super::storage_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageProfiles.def()
    }
}

impl Related<super::tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tenants.def()
    }
}

impl Related<super::upload_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
