//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "work_order_attachments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub tenant_id: Option<i32>,
    pub work_order_id: i32,
    pub upload_file_id: i32,
    pub uploaded_by_id: Option<i32>,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tenants::Entity",
        from = "Column::TenantId",
        to = "super::tenants::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Tenants,
    #[sea_orm(
        belongs_to = "super::work_orders::Entity",
        from = "Column::WorkOrderId",
        to = "super::work_orders::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkOrders,
    #[sea_orm(
        belongs_to = "super::upload_files::Entity",
        from = "Column::UploadFileId",
        to = "super::upload_files::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UploadFiles,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UploadedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    UploadedByUsers,
}

impl Related<super::work_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkOrders.def()
    }
}

impl Related<super::upload_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
