#![allow(clippy::large_stack_frames)]

use utoipa::OpenApi;

use crate::{
    controllers::{
        admin::{
            ai_images::{
                AiImageConfigRecord, AiImageGenerationBatchRecord, AiImageGenerationRecord,
                SaveAiImageConfigParams,
            },
            backups::{BackupQueryParams, BackupRecord, RestoreBackupParams, RestoreRecord},
            commands::{
                CommandRunLogQueryParams, CommandRunLogRecord, CommandRunLogTicketRecord,
                CommandRunQueryParams, CommandRunRecord, CommandTemplateQueryParams,
                CommandTemplateRecord, CommandWorkflowQueryParams, CommandWorkflowRecord,
                CommandWorkflowRunQueryParams, CommandWorkflowRunRecord,
                CommandWorkflowRunStepRecord, CommandWorkflowStepRecord, RunCommandParams,
                RunCommandWorkflowParams, SaveCommandTemplateParams, SaveCommandWorkflowParams,
                SaveCommandWorkflowStepParams,
            },
            content::{
                ContentArticleQueryParams, ContentArticleRecord, ContentCategoryQueryParams,
                ContentCategoryRecord, SaveContentArticleParams, SaveContentCategoryParams,
            },
            data_scopes::DataScopeRecord,
            departments::{DepartmentRecord, SaveDepartmentParams},
            dicts::{DictItemRecord, DictTypeRecord, SaveDictItemParams, SaveDictTypeParams},
            email_templates::{
                EmailTemplateQueryParams, EmailTemplateRecord, PreviewEmailTemplateParams,
                SaveEmailTemplateParams, TestSendEmailTemplateParams,
            },
            file_manager::{
                CreateFileFolderParams, FileBrowserParams, FileBrowserRecord, FilePathParams,
                FileRootRecord, ManagedFileRecord, RenameFileParams,
            },
            http_client::{HttpClientRuntimeConfig, HttpClientTestParams, HttpClientTestRecord},
            logs::{LogQueryParams, LogRecord},
            menus::{MenuRecord, SaveMenuParams},
            monitoring::{
                CpuCoreInfo, CpuInfo, DiskInfo, GpuInfo, HostInfo, LoadInfo, MemoryInfo,
                MonitoringOverview, NetworkInfo, ProcessQueryParams, ProcessRecord,
                ServerMonitorSnapshot,
            },
            notifications::{NotificationQueryParams, NotificationRecord, SaveNotificationParams},
            payments::{
                CreatePaymentOrderParams, CreatePaymentRefundParams, MarkPaymentPaidParams,
                PaymentCallbackQueryParams, PaymentCallbackRecord, PaymentChannelQueryParams,
                PaymentChannelRecord, PaymentChannelSummary, PaymentOrderDetailRecord,
                PaymentOrderQueryParams, PaymentOrderRecord, PaymentRefundQueryParams,
                PaymentRefundRecord, SavePaymentChannelParams,
            },
            permissions::{PermissionRecord, SavePermissionParams},
            rate_limits::{
                RateLimitEventQueryParams, RateLimitEventRecord, RateLimitQueryParams,
                RateLimitRuleRecord, SaveRateLimitRuleParams,
            },
            roles::{
                RoleDataScopeIds, RoleMenuGrant, RoleMenuGrants, RolePermissionIds, RoleRecord,
                SaveRoleParams,
            },
            scheduled_tasks::{
                SaveScheduledTaskParams, ScheduledTaskQueryParams, ScheduledTaskRecord,
                TaskRunQueryParams, TaskRunRecord,
            },
            settings::{SaveSettingParams, SettingQueryParams, SettingRecord},
            ssh::{CreateSshTicketParams, SshTargetConfig, SshTargetRecord, SshTicketRecord},
            storage_profiles::{
                SaveStorageBucketParams, SaveStorageProfileParams, StorageBucketRecord,
                StorageProfileRecord, StorageTestRecord,
            },
            tenants::{SaveTenantParams, TenantRecord},
            uploads::{
                CreateUploadFolderParams, CreateUploadTaskParams, ImportUploadObjectParams,
                ImportUploadObjectsParams, ImportUploadObjectsRecord, RenameUploadParams,
                UpdateUploadParams, UploadBrowserParams, UploadQueryParams, UploadRecord,
                UploadTaskRecord,
            },
            users_admin::{
                AssignedDepartmentRecord, AssignedRoleRecord, CreateUserParams,
                SaveUserDepartmentsParams, SaveUserRolesParams, UpdateUserParams, UserRecord,
            },
            vnc::{
                CreateVncSessionParams, VncSessionRecord, VncTargetConfig, VncTargetRecord,
                VncTicketRecord,
            },
            work_orders::{
                AssignWorkOrderParams, CreateWorkOrderAttachmentParams,
                CreateWorkOrderCommentParams, SaveWorkOrderParams, TransitionWorkOrderParams,
                WorkOrderAssignmentRecord, WorkOrderAttachmentRecord, WorkOrderCommentRecord,
                WorkOrderDetailRecord, WorkOrderQueryParams, WorkOrderRecord,
            },
        },
        auth::{
            CurrentDepartmentParams, ForgotParams, MagicLinkParams, RefreshParams,
            ResendVerificationParams, ResetParams,
        },
    },
    models::{email_templates::RenderedEmailTemplate, users::LoginParams},
    responses::{ApiResponse, EmptyData, PageParams, PageResponse},
    services::storage::{StorageBrowserRecord, StorageObjectRecord, StoragePrefixRecord},
    views::auth::{
        CurrentDataScope, CurrentDepartment, CurrentMenuActions, CurrentMenuItem, CurrentResponse,
        CurrentRole, CurrentTenant, LoginResponse, RefreshResponse,
    },
};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::controllers::auth::login,
        crate::controllers::auth::refresh,
        crate::controllers::auth::logout,
        crate::controllers::auth::current,
        crate::controllers::auth::switch_current_department,
        crate::controllers::auth::forgot,
        crate::controllers::auth::reset,
        crate::controllers::auth::magic_link,
        crate::controllers::auth::resend_verification_email,
        crate::controllers::admin::users_admin::list,
        crate::controllers::admin::users_admin::get,
        crate::controllers::admin::users_admin::create,
        crate::controllers::admin::users_admin::update,
        crate::controllers::admin::users_admin::delete,
        crate::controllers::admin::users_admin::roles,
        crate::controllers::admin::users_admin::save_roles,
        crate::controllers::admin::users_admin::departments,
        crate::controllers::admin::users_admin::save_departments,
        crate::controllers::admin::roles::list,
        crate::controllers::admin::roles::get,
        crate::controllers::admin::roles::create,
        crate::controllers::admin::roles::update,
        crate::controllers::admin::roles::delete,
        crate::controllers::admin::roles::permissions,
        crate::controllers::admin::roles::save_permissions,
        crate::controllers::admin::roles::menus,
        crate::controllers::admin::roles::save_menus,
        crate::controllers::admin::roles::data_scopes,
        crate::controllers::admin::roles::save_data_scopes,
        crate::controllers::admin::tenants::list,
        crate::controllers::admin::tenants::get,
        crate::controllers::admin::tenants::create,
        crate::controllers::admin::tenants::update,
        crate::controllers::admin::tenants::delete,
        crate::controllers::admin::departments::list,
        crate::controllers::admin::departments::get,
        crate::controllers::admin::departments::create,
        crate::controllers::admin::departments::update,
        crate::controllers::admin::departments::delete,
        crate::controllers::admin::data_scopes::list,
        crate::controllers::admin::menus::list,
        crate::controllers::admin::menus::get,
        crate::controllers::admin::menus::create,
        crate::controllers::admin::menus::update,
        crate::controllers::admin::menus::delete,
        crate::controllers::admin::permissions::list,
        crate::controllers::admin::permissions::get,
        crate::controllers::admin::permissions::create,
        crate::controllers::admin::permissions::update,
        crate::controllers::admin::permissions::delete,
        crate::controllers::admin::logs::list,
        crate::controllers::admin::logs::get,
        crate::controllers::admin::logs::delete,
        crate::controllers::admin::settings::list,
        crate::controllers::admin::settings::get,
        crate::controllers::admin::settings::create,
        crate::controllers::admin::settings::update,
        crate::controllers::admin::settings::delete,
        crate::controllers::admin::http_client::get_config,
        crate::controllers::admin::http_client::update_config,
        crate::controllers::admin::http_client::test_request,
        crate::controllers::admin::ai_images::list_configs,
        crate::controllers::admin::ai_images::create_config,
        crate::controllers::admin::ai_images::update_config,
        crate::controllers::admin::ai_images::delete_config,
        crate::controllers::admin::ai_images::list_generations,
        crate::controllers::admin::ai_images::create_generation,
        crate::controllers::admin::ai_images::preview_generation,
        crate::controllers::admin::ai_images::download_generation,
        crate::controllers::admin::ssh::targets,
        crate::controllers::admin::ssh::create_ticket,
        crate::controllers::admin::vnc::targets,
        crate::controllers::admin::vnc::sessions,
        crate::controllers::admin::vnc::create_session,
        crate::controllers::admin::vnc::create_session_ticket,
        crate::controllers::admin::vnc::close_session,
        crate::controllers::admin::email_templates::list,
        crate::controllers::admin::email_templates::get,
        crate::controllers::admin::email_templates::create,
        crate::controllers::admin::email_templates::update,
        crate::controllers::admin::email_templates::delete,
        crate::controllers::admin::email_templates::preview,
        crate::controllers::admin::email_templates::test_send,
        crate::controllers::admin::dicts::list_types,
        crate::controllers::admin::dicts::get_type,
        crate::controllers::admin::dicts::create_type,
        crate::controllers::admin::dicts::update_type,
        crate::controllers::admin::dicts::delete_type,
        crate::controllers::admin::dicts::list_items,
        crate::controllers::admin::dicts::create_item,
        crate::controllers::admin::dicts::update_item,
        crate::controllers::admin::dicts::delete_item,
        crate::controllers::admin::storage_profiles::list,
        crate::controllers::admin::storage_profiles::get,
        crate::controllers::admin::storage_profiles::create,
        crate::controllers::admin::storage_profiles::update,
        crate::controllers::admin::storage_profiles::delete,
        crate::controllers::admin::storage_profiles::list_buckets,
        crate::controllers::admin::storage_profiles::create_bucket,
        crate::controllers::admin::storage_profiles::update_bucket,
        crate::controllers::admin::storage_profiles::delete_bucket,
        crate::controllers::admin::storage_profiles::test,
        crate::controllers::admin::file_manager::roots,
        crate::controllers::admin::file_manager::browser,
        crate::controllers::admin::file_manager::create_folder,
        crate::controllers::admin::file_manager::upload,
        crate::controllers::admin::file_manager::rename,
        crate::controllers::admin::file_manager::delete,
        crate::controllers::admin::file_manager::preview,
        crate::controllers::admin::file_manager::download,
        crate::controllers::admin::uploads::list,
        crate::controllers::admin::uploads::list_tasks,
        crate::controllers::admin::uploads::create_task,
        crate::controllers::admin::uploads::upload_task_chunk,
        crate::controllers::admin::uploads::complete_task,
        crate::controllers::admin::uploads::get,
        crate::controllers::admin::uploads::create,
        crate::controllers::admin::uploads::update,
        crate::controllers::admin::uploads::delete,
        crate::controllers::admin::uploads::browser,
        crate::controllers::admin::uploads::create_folder,
        crate::controllers::admin::uploads::import_object,
        crate::controllers::admin::uploads::import_objects,
        crate::controllers::admin::uploads::rename,
        crate::controllers::admin::uploads::preview,
        crate::controllers::admin::uploads::download,
        crate::controllers::admin::notifications::list,
        crate::controllers::admin::notifications::get,
        crate::controllers::admin::notifications::create,
        crate::controllers::admin::notifications::mark_read,
        crate::controllers::admin::notifications::delete,
        crate::controllers::admin::scheduled_tasks::list,
        crate::controllers::admin::scheduled_tasks::get,
        crate::controllers::admin::scheduled_tasks::create,
        crate::controllers::admin::scheduled_tasks::update,
        crate::controllers::admin::scheduled_tasks::delete,
        crate::controllers::admin::scheduled_tasks::run,
        crate::controllers::admin::scheduled_tasks::list_runs,
        crate::controllers::admin::commands::list,
        crate::controllers::admin::commands::get,
        crate::controllers::admin::commands::create,
        crate::controllers::admin::commands::update,
        crate::controllers::admin::commands::delete,
        crate::controllers::admin::commands::list_workflows,
        crate::controllers::admin::commands::get_workflow,
        crate::controllers::admin::commands::create_workflow,
        crate::controllers::admin::commands::update_workflow,
        crate::controllers::admin::commands::delete_workflow,
        crate::controllers::admin::commands::run_workflow,
        crate::controllers::admin::commands::list_workflow_runs,
        crate::controllers::admin::commands::get_workflow_run,
        crate::controllers::admin::commands::run_template,
        crate::controllers::admin::commands::run_ad_hoc,
        crate::controllers::admin::commands::list_runs,
        crate::controllers::admin::commands::get_run,
        crate::controllers::admin::commands::list_run_logs,
        crate::controllers::admin::commands::create_log_ticket,
        crate::controllers::admin::commands::preview_run_artifact,
        crate::controllers::admin::commands::cancel_run,
        crate::controllers::admin::backups::list,
        crate::controllers::admin::backups::get,
        crate::controllers::admin::backups::create,
        crate::controllers::admin::backups::deliver,
        crate::controllers::admin::backups::list_restores,
        crate::controllers::admin::backups::restore,
        crate::controllers::admin::backups::delete,
        crate::controllers::admin::rate_limits::list,
        crate::controllers::admin::rate_limits::get,
        crate::controllers::admin::rate_limits::create,
        crate::controllers::admin::rate_limits::update,
        crate::controllers::admin::rate_limits::delete,
        crate::controllers::admin::rate_limits::list_events,
        crate::controllers::admin::monitoring::overview,
        crate::controllers::admin::monitoring::server,
        crate::controllers::admin::monitoring::processes,
        crate::controllers::admin::work_orders::list,
        crate::controllers::admin::work_orders::get,
        crate::controllers::admin::work_orders::create,
        crate::controllers::admin::work_orders::update,
        crate::controllers::admin::work_orders::delete,
        crate::controllers::admin::work_orders::transition,
        crate::controllers::admin::work_orders::list_comments,
        crate::controllers::admin::work_orders::create_comment,
        crate::controllers::admin::work_orders::assign,
        crate::controllers::admin::work_orders::list_attachments,
        crate::controllers::admin::work_orders::create_attachment,
        crate::controllers::admin::work_orders::delete_attachment,
        crate::controllers::admin::payments::list_channels,
        crate::controllers::admin::payments::create_channel,
        crate::controllers::admin::payments::get_channel,
        crate::controllers::admin::payments::update_channel,
        crate::controllers::admin::payments::delete_channel,
        crate::controllers::admin::payments::list_orders,
        crate::controllers::admin::payments::create_order,
        crate::controllers::admin::payments::get_order,
        crate::controllers::admin::payments::mark_order_paid,
        crate::controllers::admin::payments::cancel_order,
        crate::controllers::admin::payments::list_callbacks,
        crate::controllers::admin::payments::get_callback,
        crate::controllers::admin::payments::list_refunds,
        crate::controllers::admin::payments::create_refund,
        crate::controllers::admin::payments::approve_refund,
        crate::controllers::admin::payments::reject_refund,
        crate::controllers::admin::payments::mark_refund_succeeded,
        crate::controllers::admin::content::list_categories,
        crate::controllers::admin::content::get_category,
        crate::controllers::admin::content::create_category,
        crate::controllers::admin::content::update_category,
        crate::controllers::admin::content::delete_category,
        crate::controllers::admin::content::list_articles,
        crate::controllers::admin::content::get_article,
        crate::controllers::admin::content::create_article,
        crate::controllers::admin::content::update_article,
        crate::controllers::admin::content::publish_article,
        crate::controllers::admin::content::archive_article,
        crate::controllers::admin::content::delete_article,
    ),
    components(schemas(
        LoginParams,
        LoginResponse,
        RefreshParams,
        RefreshResponse,
        ForgotParams,
        ResetParams,
        MagicLinkParams,
        ResendVerificationParams,
        CurrentDepartmentParams,
        CurrentMenuActions,
        CurrentMenuItem,
        CurrentRole,
        CurrentTenant,
        CurrentDepartment,
        CurrentDataScope,
        CurrentResponse,
        EmptyData,
        PageParams,
        UserRecord,
        CreateUserParams,
        UpdateUserParams,
        AssignedRoleRecord,
        SaveUserRolesParams,
        AssignedDepartmentRecord,
        SaveUserDepartmentsParams,
        RoleRecord,
        SaveRoleParams,
        RolePermissionIds,
        RoleMenuGrant,
        RoleMenuGrants,
        RoleDataScopeIds,
        TenantRecord,
        SaveTenantParams,
        DepartmentRecord,
        SaveDepartmentParams,
        DataScopeRecord,
        MenuRecord,
        SaveMenuParams,
        PermissionRecord,
        SavePermissionParams,
        LogQueryParams,
        LogRecord,
        SettingQueryParams,
        SettingRecord,
        SaveSettingParams,
        HttpClientRuntimeConfig,
        HttpClientTestParams,
        HttpClientTestRecord,
        AiImageConfigRecord,
        SaveAiImageConfigParams,
        AiImageGenerationRecord,
        AiImageGenerationBatchRecord,
        SshTargetRecord,
        SshTargetConfig,
        CreateSshTicketParams,
        SshTicketRecord,
        VncTargetRecord,
        VncTargetConfig,
        CreateVncSessionParams,
        VncSessionRecord,
        VncTicketRecord,
        EmailTemplateQueryParams,
        EmailTemplateRecord,
        SaveEmailTemplateParams,
        PreviewEmailTemplateParams,
        TestSendEmailTemplateParams,
        RenderedEmailTemplate,
        DictTypeRecord,
        SaveDictTypeParams,
        DictItemRecord,
        SaveDictItemParams,
        StorageProfileRecord,
        SaveStorageProfileParams,
        StorageBucketRecord,
        SaveStorageBucketParams,
        StorageTestRecord,
        FileRootRecord,
        ManagedFileRecord,
        FileBrowserRecord,
        FileBrowserParams,
        FilePathParams,
        CreateFileFolderParams,
        RenameFileParams,
        UploadQueryParams,
        UploadBrowserParams,
        UploadRecord,
        UploadTaskRecord,
        UpdateUploadParams,
        ImportUploadObjectParams,
        ImportUploadObjectsParams,
        ImportUploadObjectsRecord,
        CreateUploadFolderParams,
        RenameUploadParams,
        CreateUploadTaskParams,
        StorageBrowserRecord,
        StoragePrefixRecord,
        StorageObjectRecord,
        NotificationQueryParams,
        NotificationRecord,
        SaveNotificationParams,
        ScheduledTaskQueryParams,
        ScheduledTaskRecord,
        SaveScheduledTaskParams,
        TaskRunQueryParams,
        TaskRunRecord,
        BackupQueryParams,
        BackupRecord,
        RestoreBackupParams,
        RestoreRecord,
        RateLimitQueryParams,
        RateLimitRuleRecord,
        SaveRateLimitRuleParams,
        RateLimitEventQueryParams,
        RateLimitEventRecord,
        MonitoringOverview,
        ServerMonitorSnapshot,
        HostInfo,
        CpuInfo,
        CpuCoreInfo,
        MemoryInfo,
        DiskInfo,
        NetworkInfo,
        GpuInfo,
        LoadInfo,
        ProcessQueryParams,
        ProcessRecord,
        WorkOrderQueryParams,
        WorkOrderRecord,
        WorkOrderDetailRecord,
        WorkOrderCommentRecord,
        WorkOrderAssignmentRecord,
        WorkOrderAttachmentRecord,
        SaveWorkOrderParams,
        TransitionWorkOrderParams,
        CreateWorkOrderCommentParams,
        AssignWorkOrderParams,
        CreateWorkOrderAttachmentParams,
        PaymentChannelQueryParams,
        PaymentChannelRecord,
        PaymentChannelSummary,
        SavePaymentChannelParams,
        PaymentOrderQueryParams,
        PaymentOrderRecord,
        PaymentOrderDetailRecord,
        CreatePaymentOrderParams,
        MarkPaymentPaidParams,
        PaymentCallbackQueryParams,
        PaymentCallbackRecord,
        PaymentRefundQueryParams,
        PaymentRefundRecord,
        CreatePaymentRefundParams,
        ContentCategoryQueryParams,
        ContentCategoryRecord,
        SaveContentCategoryParams,
        ContentArticleQueryParams,
        ContentArticleRecord,
        SaveContentArticleParams,
        PageResponse<UserRecord>,
        PageResponse<RoleRecord>,
        PageResponse<TenantRecord>,
        PageResponse<DepartmentRecord>,
        PageResponse<StorageProfileRecord>,
        PageResponse<PermissionRecord>,
        PageResponse<LogRecord>,
        PageResponse<SettingRecord>,
        PageResponse<EmailTemplateRecord>,
        PageResponse<DictTypeRecord>,
        PageResponse<UploadRecord>,
        PageResponse<NotificationRecord>,
        PageResponse<ScheduledTaskRecord>,
        PageResponse<TaskRunRecord>,
        PageResponse<BackupRecord>,
        PageResponse<RateLimitRuleRecord>,
        PageResponse<RateLimitEventRecord>,
        PageResponse<ProcessRecord>,
        PageResponse<WorkOrderRecord>,
        PageResponse<PaymentChannelRecord>,
        PageResponse<PaymentOrderRecord>,
        PageResponse<PaymentCallbackRecord>,
        PageResponse<PaymentRefundRecord>,
        PageResponse<ContentCategoryRecord>,
        PageResponse<ContentArticleRecord>,
        ApiResponse<EmptyData>,
        ApiResponse<LoginResponse>,
        ApiResponse<RefreshResponse>,
        ApiResponse<CurrentResponse>,
        ApiResponse<UserRecord>,
        ApiResponse<PageResponse<UserRecord>>,
        ApiResponse<Vec<AssignedRoleRecord>>,
        ApiResponse<Vec<AssignedDepartmentRecord>>,
        ApiResponse<RoleRecord>,
        ApiResponse<PageResponse<RoleRecord>>,
        ApiResponse<RolePermissionIds>,
        ApiResponse<RoleMenuGrants>,
        ApiResponse<RoleDataScopeIds>,
        ApiResponse<TenantRecord>,
        ApiResponse<PageResponse<TenantRecord>>,
        ApiResponse<DepartmentRecord>,
        ApiResponse<PageResponse<DepartmentRecord>>,
        ApiResponse<StorageProfileRecord>,
        ApiResponse<PageResponse<StorageProfileRecord>>,
        ApiResponse<Vec<StorageBucketRecord>>,
        ApiResponse<StorageBucketRecord>,
        ApiResponse<StorageTestRecord>,
        ApiResponse<Vec<FileRootRecord>>,
        ApiResponse<FileBrowserRecord>,
        ApiResponse<ManagedFileRecord>,
        ApiResponse<Vec<DataScopeRecord>>,
        ApiResponse<MenuRecord>,
        ApiResponse<Vec<MenuRecord>>,
        ApiResponse<PermissionRecord>,
        ApiResponse<PageResponse<PermissionRecord>>,
        ApiResponse<LogRecord>,
        ApiResponse<PageResponse<LogRecord>>,
        ApiResponse<SettingRecord>,
        ApiResponse<PageResponse<SettingRecord>>,
        ApiResponse<HttpClientRuntimeConfig>,
        ApiResponse<HttpClientTestRecord>,
        ApiResponse<Vec<AiImageConfigRecord>>,
        ApiResponse<AiImageConfigRecord>,
        ApiResponse<PageResponse<AiImageGenerationRecord>>,
        ApiResponse<AiImageGenerationBatchRecord>,
        ApiResponse<Vec<SshTargetRecord>>,
        ApiResponse<SshTicketRecord>,
        ApiResponse<Vec<VncTargetRecord>>,
        ApiResponse<Vec<VncSessionRecord>>,
        ApiResponse<VncSessionRecord>,
        ApiResponse<VncTicketRecord>,
        ApiResponse<EmailTemplateRecord>,
        ApiResponse<PageResponse<EmailTemplateRecord>>,
        ApiResponse<RenderedEmailTemplate>,
        ApiResponse<DictTypeRecord>,
        ApiResponse<PageResponse<DictTypeRecord>>,
        ApiResponse<Vec<DictItemRecord>>,
        ApiResponse<DictItemRecord>,
        ApiResponse<UploadRecord>,
        ApiResponse<PageResponse<UploadRecord>>,
        ApiResponse<UploadTaskRecord>,
        ApiResponse<Vec<UploadTaskRecord>>,
        ApiResponse<ImportUploadObjectsRecord>,
        ApiResponse<StorageBrowserRecord>,
        ApiResponse<StoragePrefixRecord>,
        ApiResponse<NotificationRecord>,
        ApiResponse<PageResponse<NotificationRecord>>,
        ApiResponse<ScheduledTaskRecord>,
        ApiResponse<PageResponse<ScheduledTaskRecord>>,
        ApiResponse<TaskRunRecord>,
        ApiResponse<PageResponse<TaskRunRecord>>,
        ApiResponse<BackupRecord>,
        ApiResponse<PageResponse<BackupRecord>>,
        ApiResponse<RestoreRecord>,
        ApiResponse<Vec<RestoreRecord>>,
        ApiResponse<RateLimitRuleRecord>,
        ApiResponse<PageResponse<RateLimitRuleRecord>>,
        ApiResponse<PageResponse<RateLimitEventRecord>>,
        ApiResponse<MonitoringOverview>,
        ApiResponse<ServerMonitorSnapshot>,
        ApiResponse<PageResponse<ProcessRecord>>,
        ApiResponse<WorkOrderRecord>,
        ApiResponse<WorkOrderDetailRecord>,
        ApiResponse<PageResponse<WorkOrderRecord>>,
        ApiResponse<Vec<WorkOrderCommentRecord>>,
        ApiResponse<WorkOrderCommentRecord>,
        ApiResponse<Vec<WorkOrderAttachmentRecord>>,
        ApiResponse<WorkOrderAttachmentRecord>,
        ApiResponse<PaymentChannelRecord>,
        ApiResponse<PageResponse<PaymentChannelRecord>>,
        ApiResponse<PaymentOrderRecord>,
        ApiResponse<PaymentOrderDetailRecord>,
        ApiResponse<PageResponse<PaymentOrderRecord>>,
        ApiResponse<PaymentCallbackRecord>,
        ApiResponse<PageResponse<PaymentCallbackRecord>>,
        ApiResponse<PaymentRefundRecord>,
        ApiResponse<PageResponse<PaymentRefundRecord>>,
        ApiResponse<ContentCategoryRecord>,
        ApiResponse<PageResponse<ContentCategoryRecord>>,
        ApiResponse<ContentArticleRecord>,
        ApiResponse<PageResponse<ContentArticleRecord>>,
        CommandTemplateQueryParams,
        CommandTemplateRecord,
        SaveCommandTemplateParams,
        RunCommandParams,
        CommandRunQueryParams,
        CommandRunRecord,
        CommandRunLogQueryParams,
        CommandRunLogRecord,
        CommandRunLogTicketRecord,
        CommandWorkflowQueryParams,
        CommandWorkflowRecord,
        CommandWorkflowStepRecord,
        SaveCommandWorkflowParams,
        SaveCommandWorkflowStepParams,
        RunCommandWorkflowParams,
        CommandWorkflowRunQueryParams,
        CommandWorkflowRunRecord,
        CommandWorkflowRunStepRecord,
        ApiResponse<CommandTemplateRecord>,
        ApiResponse<PageResponse<CommandTemplateRecord>>,
        ApiResponse<CommandRunRecord>,
        ApiResponse<PageResponse<CommandRunRecord>>,
        ApiResponse<Vec<CommandRunLogRecord>>,
        ApiResponse<CommandRunLogTicketRecord>,
        ApiResponse<CommandWorkflowRecord>,
        ApiResponse<PageResponse<CommandWorkflowRecord>>,
        ApiResponse<CommandWorkflowRunRecord>,
        ApiResponse<PageResponse<CommandWorkflowRunRecord>>
    )),
    tags(
        (name = "auth", description = "Authentication and token lifecycle endpoints"),
        (name = "admin-users", description = "Admin user management endpoints"),
        (name = "admin-roles", description = "Admin role and authorization assignment endpoints"),
        (name = "admin-tenants", description = "Admin tenant management endpoints"),
        (name = "admin-departments", description = "Admin department management endpoints"),
        (name = "admin-data-scopes", description = "Admin data scope endpoints"),
        (name = "admin-menus", description = "Admin menu management endpoints"),
        (name = "admin-permissions", description = "Admin API and button permission endpoints"),
        (name = "admin-logs", description = "Admin operation and login log endpoints"),
        (name = "admin-settings", description = "Admin system setting endpoints"),
        (name = "admin-http-client", description = "Admin global HTTP client runtime configuration endpoints"),
        (name = "admin-ai-images", description = "Admin AI image configuration and generation endpoints"),
        (name = "admin-ssh", description = "Admin SSH terminal endpoints"),
        (name = "admin-vnc", description = "Admin VNC viewer endpoints"),
        (name = "admin-email-templates", description = "Admin email template endpoints"),
        (name = "admin-dicts", description = "Admin dictionary type and item endpoints"),
        (name = "admin-storage", description = "Admin storage profile and bucket endpoints"),
        (name = "admin-files", description = "Admin local URL-mapped file management endpoints"),
        (name = "admin-uploads", description = "Admin upload and material library endpoints"),
        (name = "admin-notifications", description = "Admin notification center endpoints"),
        (name = "admin-scheduled-tasks", description = "Admin scheduled task endpoints"),
        (name = "admin-commands", description = "Admin command template and execution endpoints"),
        (name = "admin-backups", description = "Admin database backup endpoints"),
        (name = "admin-rate-limits", description = "Admin rate limit endpoints"),
        (name = "admin-monitoring", description = "Admin monitoring endpoints"),
        (name = "admin-work-orders", description = "Admin work order endpoints"),
        (name = "admin-payments", description = "Admin payment management endpoints"),
        (name = "admin-content", description = "Admin content management endpoints")
    )
)]
pub struct ApiDoc;
